const app = document.getElementById('site-app');
const logo = '/assets/gepremtek-logo.jpg';
const phone = '09153828173';
const whatsapp = '2349153828173';

function layout() {
  return `
  <div class="topbar"><div class="container"><span>Professional Engineering & Electrical Services</span><span class="hide-mobile">📞 <a href="tel:${phone}">${phone}</a> &nbsp; | &nbsp; ✉ gepremtekservices@gmail.com</span></div></div>
  <header class="nav"><div class="container nav-inner">
    <a class="brand" href="/#home"><img src="${logo}" alt="Gepremtek Services Nigeria Limited logo"><span><strong>Gepremtek Services<br> Nigeria Limited</strong><small>Engineering • Electrical • Power</small></span></a>
    <button class="menu" id="menuBtn" aria-label="Open menu">☰</button>
    <nav class="nav-links" id="navLinks"><a href="/#home">Home</a><a href="/#about">About</a><a href="/#services">Services</a><a href="/#projects">Projects</a><a href="/#contact">Contact</a><a class="nav-cta" href="/#contact">Request a Quote</a></nav>
  </div></header>
  `;
}

function home() {
  app.innerHTML = layout() + `
  <main>
    <section class="hero" id="home"><div class="container hero-grid">
      <div><span class="eyebrow">⚙ Trusted Engineering Partner</span><h1>Powering better projects with <span>professional engineering.</span></h1><p>Gepremtek Services Nigeria Limited provides dependable electrical installation, maintenance, contracting, material supply and power solutions for homes, businesses and industrial projects.</p><div class="hero-actions"><a class="btn btn-primary" href="#contact">Get a Free Quote →</a><a class="btn btn-outline" href="#services">Explore Services</a></div></div>
      <div class="hero-card"><img src="https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=1000&q=85" alt="Electrical engineering technician at work"><div class="hero-badge"><div><strong>Built for reliability.</strong><span>Quality workmanship. Safety first.</span></div><div class="badge-dot">✓</div></div></div>
    </div></section>
    <div class="container trust"><div class="trust-grid"><div class="trust-item"><strong>Electrical</strong><span>Installation & contracting</span></div><div class="trust-item"><strong>Maintenance</strong><span>Repairs & technical support</span></div><div class="trust-item"><strong>Power</strong><span>Solar & backup solutions</span></div><div class="trust-item"><strong>Supply</strong><span>Quality electrical materials</span></div></div></div>

    <section class="section" id="about"><div class="container about-grid"><div class="about-panel"><img src="${logo}" alt="Gepremtek logo"><h3>Engineering you can depend on.</h3><p>We combine technical expertise, quality materials and practical project delivery to help clients build safer and more dependable electrical systems.</p></div><div><span class="kicker">About Gepremtek</span><h2>Professional service from planning to completion.</h2><p>Gepremtek Services Nigeria Limited is an engineering services company focused on electrical and power solutions. Our goal is simple: deliver dependable work, clear communication and solutions that serve our customers for the long term.</p><ul class="check-list"><li><b>✓</b><span><strong>Safety-led execution</strong><br>We prioritize safe installation and responsible engineering practices.</span></li><li><b>✓</b><span><strong>Quality-focused delivery</strong><br>We aim for clean workmanship and dependable project outcomes.</span></li><li><b>✓</b><span><strong>Customer-first support</strong><br>From enquiry to maintenance, we keep the service practical and responsive.</span></li></ul></div></div></section>

    <section class="section alt" id="services"><div class="container"><div class="section-head"><span class="kicker">What we do</span><h2>Complete electrical & engineering services.</h2><p>From materials and installation to maintenance and power solutions, our services are designed to support projects at every stage.</p></div><div class="service-grid" id="serviceGrid"></div></div></section>

    <section class="section" id="projects"><div class="container"><div class="section-head"><span class="kicker">Project capability</span><h2>Work built around real-world needs.</h2><p>Our project approach focuses on dependable systems, careful installation and professional technical execution.</p></div><div class="project-grid" id="projectGrid"></div></div></section>

    <section class="section alt"><div class="container why-grid"><div><span class="kicker">Why choose us</span><h2>A partner focused on doing the job right.</h2><p>We bring a practical engineering mindset to each engagement, with attention to safety, quality, communication and long-term system performance.</p><div class="stats"><div class="stat"><strong>01</strong><span>Safety & quality mindset</span></div><div class="stat"><strong>02</strong><span>Professional project delivery</span></div><div class="stat"><strong>03</strong><span>Responsive customer support</span></div><div class="stat"><strong>04</strong><span>Multi-service capability</span></div></div></div><div class="quote-box"><h3>Need an electrical or engineering solution?</h3><p>Tell us what you need. Our team can review your request and discuss the right approach for your project.</p><a class="btn btn-primary" href="#contact">Talk to Gepremtek →</a></div></div></section>

    <section class="section" id="contact"><div class="container contact-grid"><div><span class="kicker">Contact us</span><h2>Let’s discuss your next project.</h2><p>Send your request and we’ll get back to you. You can also call or WhatsApp us directly.</p><div class="contact-card"><div class="contact-line"><div class="contact-icon">📍</div><div><b>Office</b><span>39/41 Brown Street, Oshodi, Lagos State, Nigeria</span></div></div><div class="contact-line"><div class="contact-icon">☎</div><div><b>Phone / WhatsApp</b><a href="https://wa.me/${whatsapp}" target="_blank" rel="noreferrer">${phone}</a></div></div><div class="contact-line"><div class="contact-icon">✉</div><div><b>Email</b><a href="mailto:gepremtekservices@gmail.com">gepremtekservices@gmail.com</a></div></div></div></div>
      <div class="quote-box"><h3>Request a quote</h3><p>Required fields are marked by the form. Your enquiry is securely sent to the website backend.</p><div id="formNotice" class="notice"></div><form class="form" id="quoteForm"><div class="form-row"><div class="field"><label>Name *</label><input name="name" required placeholder="Your full name"></div><div class="field"><label>Phone *</label><input name="phone" required placeholder="080..." inputmode="tel"></div></div><div class="form-row"><div class="field"><label>Email</label><input name="email" type="email" placeholder="you@example.com"></div><div class="field"><label>Service *</label><select name="service" required><option value="">Select a service</option><option>Electrical Contracting</option><option>Electrical Installation</option><option>Maintenance & Repairs</option><option>Sales of Electrical Materials</option><option>Solar & Power Solutions</option><option>General Engineering Services</option></select></div></div><div class="field"><label>Project details *</label><textarea name="message" required placeholder="Tell us about your project or what you need..."></textarea></div><button class="btn btn-primary" type="submit">Submit Request</button></form></div>
    </div></section>
  </main>
  <footer class="footer"><div class="container"><div class="footer-grid"><div><a class="brand" href="#home"><img src="${logo}" alt="Gepremtek logo"><span><strong>Gepremtek Services Nigeria Limited</strong></span></a><p>Professional electrical, engineering, maintenance and power services.</p></div><div><h3>Company</h3><a href="#about">About Us</a><a href="#services">Services</a><a href="#projects">Projects</a></div><div><h3>Services</h3><a href="#services">Electrical Installation</a><a href="#services">Maintenance</a><a href="#services">Solar & Power</a></div><div><h3>Contact</h3><a href="tel:${phone}">${phone}</a><a href="mailto:gepremtekservices@gmail.com">gepremtekservices@gmail.com</a><a href="#contact">Request a Quote</a></div></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} Gepremtek Services Nigeria Limited. All rights reserved.</span><span>Professional engineering. Dependable results.</span></div></div></footer><a class="float-wa" href="https://wa.me/${whatsapp}?text=Hello%20Gepremtek%20Services%2C%20I%20would%20like%20to%20make%20an%20enquiry." target="_blank" rel="noreferrer" aria-label="Chat on WhatsApp">◔</a>`;
  loadContent(); bindSite();
}

async function loadContent(){
  try{const [s,p]=await Promise.all([fetch('/api/services'),fetch('/api/projects')]); const services=await s.json(), projects=await p.json();
    document.getElementById('serviceGrid').innerHTML=services.map(x=>`<article class="service-card"><div class="service-icon">${x.icon}</div><h3>${x.title}</h3><p>${x.text}</p></article>`).join('');
    document.getElementById('projectGrid').innerHTML=projects.map(x=>`<article class="project"><img src="${x.image}" alt="${x.title}" loading="lazy"><div class="project-caption"><span>${x.category}</span><h3>${x.title}</h3></div></article>`).join('');
  }catch(e){console.error(e)}
}
function bindSite(){
  const menu=document.getElementById('menuBtn'), links=document.getElementById('navLinks');
  menu?.addEventListener('click',()=>links.classList.toggle('open'));
  links?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>links.classList.remove('open')));
  document.getElementById('quoteForm')?.addEventListener('submit', async e=>{e.preventDefault();const form=e.currentTarget, notice=document.getElementById('formNotice'); const btn=form.querySelector('button'); btn.disabled=true; btn.textContent='Sending…';
    try{const data=Object.fromEntries(new FormData(form)); const r=await fetch('/api/inquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}); const out=await r.json(); if(!r.ok) throw new Error(out.error||'Unable to send'); notice.className='notice show success';notice.textContent=out.message;form.reset();}catch(err){notice.className='notice show error';notice.textContent=err.message}finally{btn.disabled=false;btn.textContent='Submit Request'}
  });
}

function admin(){
  const token=localStorage.getItem('gepremtek_admin_token');
  if(!token){ app.innerHTML=`<div class="admin-page"><div class="login-card"><img src="${logo}" alt="Gepremtek logo"><h1>Admin Dashboard</h1><p>Sign in to manage customer enquiries.</p><div id="loginNotice" class="notice"></div><form id="loginForm" class="form"><div class="field"><label>Email</label><input name="email" type="email" required value=""></div><div class="field"><label>Password</label><input name="password" type="password" required></div><button class="btn btn-primary" type="submit">Sign in</button></form><p style="font-size:.8rem;color:#647383;margin-bottom:0">Use the ADMIN_EMAIL and ADMIN_PASSWORD values configured on your server.</p></div></div>`; document.getElementById('loginForm').addEventListener('submit', login); return;}
  app.innerHTML=`<div class="admin-page"><div class="admin-wrap"><div class="admin-head"><div><div class="kicker">Gepremtek</div><h1>Admin Dashboard</h1></div><button class="btn" style="background:#e9eef2;color:#193249" id="logout">Log out</button></div><div class="admin-grid"><div class="admin-stat"><strong id="total">—</strong><span>Total enquiries</span></div><div class="admin-stat"><strong id="newCount">—</strong><span>New enquiries</span></div><div class="admin-stat"><strong id="closedCount">—</strong><span>Closed enquiries</span></div></div><div id="adminNotice" class="notice"></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Customer</th><th>Service</th><th>Message</th><th>Date</th><th>Status</th><th>Action</th></tr></thead><tbody id="inquiryRows"></tbody></table></div></div></div>`;
  document.getElementById('logout').onclick=()=>{localStorage.removeItem('gepremtek_admin_token');admin()}; loadInquiries();
}
async function login(e){e.preventDefault();const notice=document.getElementById('loginNotice');try{const body=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.error);localStorage.setItem('gepremtek_admin_token',data.token);admin()}catch(err){notice.className='notice show error';notice.textContent=err.message}}
async function loadInquiries(){try{const token=localStorage.getItem('gepremtek_admin_token');const r=await fetch('/api/admin/inquiries',{headers:{Authorization:`Bearer ${token}`}});if(r.status===401){localStorage.removeItem('gepremtek_admin_token');return admin()}const items=await r.json();document.getElementById('total').textContent=items.length;document.getElementById('newCount').textContent=items.filter(x=>x.status==='new').length;document.getElementById('closedCount').textContent=items.filter(x=>x.status==='closed').length;document.getElementById('inquiryRows').innerHTML=items.length?items.map(x=>`<tr><td><strong>${esc(x.name)}</strong><br><small>${esc(x.phone)}<br>${esc(x.email||'')}</small></td><td>${esc(x.service)}</td><td style="max-width:280px">${esc(x.message)}</td><td>${new Date(x.createdAt).toLocaleString()}</td><td><select data-status="${x.id}"><option ${x.status==='new'?'selected':''}>new</option><option ${x.status==='in-progress'?'selected':''}>in-progress</option><option ${x.status==='closed'?'selected':''}>closed</option></select></td><td><button data-delete="${x.id}" class="btn" style="background:#ffe8e8;color:#8b1c1c;padding:8px 12px">Delete</button></td></tr>`).join(''):`<tr><td colspan="6" style="text-align:center;padding:35px">No enquiries yet.</td></tr>`;document.querySelectorAll('[data-status]').forEach(s=>s.onchange=()=>updateStatus(s.dataset.status,s.value));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteInquiry(b.dataset.delete));}catch(e){document.getElementById('adminNotice').className='notice show error';document.getElementById('adminNotice').textContent=e.message}}
function esc(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function updateStatus(id,status){const token=localStorage.getItem('gepremtek_admin_token');await fetch(`/api/admin/inquiries/${id}`,{method:'PATCH',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({status})});loadInquiries()}
async function deleteInquiry(id){if(!confirm('Delete this enquiry?'))return;const token=localStorage.getItem('gepremtek_admin_token');await fetch(`/api/admin/inquiries/${id}`,{method:'DELETE',headers:{Authorization:`Bearer ${token}`}});loadInquiries()}

if(location.pathname.startsWith('/admin')) admin(); else home();
